version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/
    
permissions:
- object: /
   pattern: "**"
   owner: ec2-user
   group: ec2-user
   
hooks:
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 3000
      runas: ec2-user
  AfterInstall:
    - location: scripts/initialize.sh
      timeout: 3000
      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 3000
      runas: ec2-user
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 3000
      runas: ec2-user
